#ifndef LIBFACTORGRAPH_GLOBAL_H
#define LIBFACTORGRAPH_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBFACTORGRAPH_LIBRARY)
#  define LIBFACTORGRAPHSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBFACTORGRAPHSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBFACTORGRAPH_GLOBAL_H
